### ISSUE TITLE
[FEATURE] Add support for folder in generate_hcl block

### ISSUE THREAD

**Issue by smalot** [mineiros-io/terramate#503]
Hi,

When dealing with multiple generated files from different modules, it could interesting to isolate generated files into some folders instead of simply use a "_" to order files.

Currently, the char "/" is not allowed in the file name making it impossible.

Many thanks

**Comment by katcipis** [comment]
Hi @smalot,

The current limitation is by design, so indeed you can't use folders when generating code on Terramate today. We already had a few discussions on how code generation could behave for specific folders but we have no ETA on when that is going to happen as we are currently working on other features.

**Comment by katcipis** [comment]
@smalot the release [v0.1.36](https://github.com/mineiros-io/terramate/releases/tag/v0.1.36) should address your issue. Let me know if it works for you.
