### ISSUE TITLE
[FEATURE] Regex for watcher

### ISSUE THREAD

**Issue by geowatson** [mineiros-io/terramate#863]
**Is your feature request related to a problem? Please describe.**
When you need to watch changes from more than 10 files it gets somewhat hard to remember to add new files to `stack.watch`.

**Describe the solution you'd like**
Currently there is that:

```terraform
stack {
  ...
  watch = [
    "customtemplates/template1.tftpl",
    "customtemplates/template2.tftpl",
    "customtemplates/template3.tftpl",
    "jsons/file1.json",
    "jsons/file2.json",
    "jsons/file3.json"
  ]
}
```

Could be more readable and easily manageable this way:
```terraform
stack {
  ...
  watch = [
    "customtemplates/*.tftpl",
    "jsons/*.json"
  ]
}
```

**Describe alternatives you've considered**
For now I'm adding all filepaths that needs to be watched manually for each file.

**Additional context**
Thanks.

**Comment by i4ki** [comment]
Hi @geowatson 

Supporting regex in the `stack.watch` attribute was discussed before but not decided yet if it's the best feature for this use case (because using filesystem functions can achieve similar behavior -- see explanation below).

But talking about your examples, by default Terramate already watches all subdirs of the stack for changes, then your sample code is redundant. Or maybe you meant that `customtemplates/` and `jsons/` are directories outside the stack tree, if that's the case, then you can use the `tm_fileset()` function to pattern match the file names. You can use funcalls in the `after`, `before`, `wants`, `wanted_by` and `watch` fields but **no variable (`global`, `terramate`, etc) is supported**. See below:

```
$ tree .
.
├── config.tm
├── customtemplates
│   ├── template1.tftpl
│   ├── template2.tftpl
│   └── template3.tftpl
├── jsons
│   ├── file1.json
│   ├── file2.json
│   └── file3.json
└── stack
    └── stack.tm

4 directories, 8 files
```

Then the `stack.tm` file below will do wildcard matching on the files in both directories `/customtemplates` and `/jsons`:

```hcl
stack {
  watch = [for fname in tm_concat(
      tm_tolist(tm_fileset("..", "customtemplates/*.tftpl")),
      tm_tolist(tm_fileset("..", "jsons/*.json")),
    ) : "/${fname}"
  ]
}
```
The `tm_tolist()` is required because `tm_fileset()` returns a `set(string)` but `tm_concat()` expects `list` arguments.
The code above will set `stack.watch` with the value:
```
[
    "/customtemplates/template1.tftpl",
    "/customtemplates/template2.tftpl",
    "/customtemplates/template3.tftpl",
    "/jsons/file1.json",
    "/jsons/file2.json",
    "/jsons/file3.json",
]
```

Let me know if this helps you.

_I just noticed that it's quite difficult to debug the `stack.watch` (and other fields) of the stack block, as they are not exposed anywhere as metadata. I will discuss with @mariux ways of improving this._

**Comment by geowatson** [comment]
@i4ki Unfortunately in my case json files that are being modified are not exactly following the default watcher behavior, so if I omit `watch` directive on this file from stack it will not detect any changes:

```terraform
# somewhere in terraform file

... = file("jsons/file1.json") # changes in file1.json does not trigger watcher by default
```

**Comment by mariux** [comment]
@geowatson could you elaborate on the details? without a `watch` setting in the stack the files referenced in functions won't be considered..

**Comment by i4ki** [comment]
hey @geowatson 
is the jsons directory or the files being `gitignored`? if so they will indeed be ignored by the change detector.

**Comment by mariux** [comment]
In your initial post you reference files as relative inside the stack.. Those files should be triggering a change detection anyway if not included in `.gitignore`.

Every file inside a stack is considered to trigger the stack as changed if the file changes.. this includes sub directories unless a sub directory is a stack itself. Files in child stacks are not trigger a parent stack as changed.

So i wonder why it does not work. Could you share a tree view?


p.s.:

An easier to maintain version for searching from root of the project will be

```hcl
  watch = tm_setunion(tm_flatten([
    for pattern in [
      "/customtemplates/*",
      "/jsons/*.json",
    ] : tm_fileset("", "${terramate.stack.path.to_root}${pattern}")
  ]))
```

which searches from the root of the project and allows to move the stack through the hierarchy later on.

**Comment by mariux** [comment]
in addition all the files need to be already committed for git to detect them as changed. You can validate this with `git diff --name-only HEAD^` on `main` branch and `git diff --name-only origin/main` on any other branch. If this includes a watched file or a file belonging to the stack, the stack will be identified as changed. 

can you confirm those constraints are true in your case?

**Comment by geowatson** [comment]
Okay, so I tested watcher behavior locally and it indeed does work as intended, every update in stack is getting changes from `git-diff-tree`, if files are placed inside the stack. 

I am sure that this is quite enough for making `terramate run -B origin/main -c terraform plan` and `terramate run -B origin/main -c terraform apply` from branch feature during MR.

Thanks!

**Comment by soerenmartius** [comment]
Thanks for getting back to us @geowatson ! Great that we could resolve this. Let us know if any help is needed in the future.
