### ISSUE TITLE
[FEATURE] Indicate source config file for generate_hcl and generate_file 

### ISSUE THREAD

**Issue by az-z** [mineiros-io/terramate#887]
**Is your feature request related to a problem? Please describe.**
currently ( version 0.2.16) the file generated by generate_hcl and generate_file have the following record:
```// TERRAMATE: GENERATED AUTOMATICALLY DO NOT EDIT```
It may be beneficial during troubleshooting to know what source config was used

**Describe the solution you'd like**
the output changed to:
```
// TERRAMATE: GENERATED AUTOMATICALLY DO NOT EDIT
//source config: /<path to>/<config file>
```
**Describe alternatives you've considered**
none I can think of.

**Comment by i4ki** [comment]
Hi @az-z 

Terramate used to work like that but we removed this information because it changed the generated code whenever we moved code around (eg.: refactoring generate blocks, moving stacks around, etc) and then it marked stacks as changed (when using `--changed`).

In the same release that we removed the *source config* information, we added the `terramate experimental generate debug` command which shows which source generates each generated file.
Please, try it out.

We know it's not the best/ideal solution but we are aware that this could be improved somehow making the change detector ignore non-important aspects of the file change.

**Comment by az-z** [comment]
@i4ki ,
i get : 
```
terramate experimental generate debug
/Clients/NYDSS/dev/netsec/backend.tf origin: /config.tm:2,1-35,2
/Clients/NYDSS/dev/netsec/terraform.tfvars origin: /Clients/NYDSS/dev/netsec/config.tm:8,1-37,2
/Clients/NYDSS/dev/smsms/backend.tf origin: /config.tm:2,1-35,2
/Clients/NYDSS/dev/smsms/terraform.tfvars origin: /Clients/NYDSS/dev/smsms/config.tm:11,1-45,2
/Clients/NYDSS/prod/smsms/backend.tf origin: /config.tm:2,1-35,2
```
this is helpful. Thank you for pointing out.

at the same time I'd expect this output as part of the "verbose" flag ( I remember @mariux mentioned you are reworking this portion).

Even if git marks the file as changed, it may be a good outcome, since that will force the execution of TF => the user will verify that even after the code refactoring there were no unexpected changes introduced.  I'd rather pay in 30 seconds to receive an empty plan than spend hours trying to redo iac later.

**Comment by mariux** [comment]
Thanks for the feedback..

I added the following two items to our backlog
- Allow to enable rendering origin of generated code into magic header
- Add support to display origin of generated code into language server & VSCode Extension

> Even if git marks the file as changed, it may be a good outcome, since that will force the execution of TF => the user will verify that even after the code refactoring there were no unexpected changes introduced. I'd rather pay in 30 seconds to receive an empty plan than spend hours trying to redo iac later.

If generation does not regenerate files, you already know that no unexpected changes occur. There is not need to enforce execution of the stacks.

We have customers using this on scale where a refactor (rename of origin files) triggered 500+ stacks as changed, that's why we removed it in the first place. But making this a decision of the user makes sense.

Can we close this for now?
